version: 2.1

orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install

  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a heroku-kw
            heroku container:push web -a heroku-kw
            heroku container:release web -a heroku-kw
  # build-and-push:
  #   docker:
  #     - image: cimg/base:current
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - docker/check:
  #         docker-username: DOCKER_USERNAME
  #         docker-password: DOCKER_PASSWORD
  #     - docker/build:
  #         image: $DOCKER_USERNAME/education-space
  #         tag: latest
  #     - docker/push:
  #         image: $DOCKER_USERNAME/education-space
  #         tag: latest

workflows:
  main_workflow:
    when: << pipeline.git.branch == "main" >>
    jobs:
      - build
      - test:
          requires:
            - build

  release_workflow:
    when: << pipeline.git.branch == "release" >>
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      # - build-and-push:
      #     requires:
      #       - test
      #     context:
      #       - docker-hub-creds