version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install

  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test

  build-and-push:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - run:
          name: Build Docker Image
          command: |
            echo "Building Docker image"
            docker build -t education-space/app:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "Pushing Docker image to Docker Hub"
            docker push education-space/app:latest

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - build-and-push:
          requires:
            - test